name: demo-action

on:
  push:
    branches: main
jobs:
  build: 
    runs-on: ubantu-letest
    steps: 
       - uses: actions/checkout@v4.2.2
       - name: run a sample job
       - run : echo hello world
         
